[package]
name = "pulseseek-decoder-symphonia"
version = "1.0.5"
edition = "2021"
license = "MPL-2.0"

[dependencies]
pulseseek-domain = { path = "../pulseseek-domain" }
symphonia = { version = "0.5", default-features = false, features = ["wav", "aiff", "pcm", "flac", "mp3", "ogg", "vorbis", "isomp4", "aac", "alac"] }

[dev-dependencies]
tempfile = "3"
